facebook:
  verify: "glosa-bot"
  page-access-token: EAAMosFUni9wBAFAu5lYzqaMhtlg0RLhxQNZCt1QtOHfzVsA1daZCZByxwfAl8MSTdpZA1MJcQyYF9S1YwHqZCxYbh42DbL6vzblvFtoY83PjlHBhyuwn2uU8cgZCWE7w8ZCXyB0dAPW1siOdEKdUF61zWMqZBb0tpemBw0hgxLxOQf4e5LoIA1gx
  secret: 2bb2a236b7335cc58fc1c66d686e4f2a