facebook:
  verify: "glosa-bot"
  page-access-token: EAAMosFUni9wBADjFhvQMxfKS1VPlPCDuaHFiG9XMY3PcTUewzcYAr2SkQGnYUrffvJDV2lUhoMMtj29wRw7dvY8O9oKQX0JaNd9Bcy8dWiL2VBrd2XZCnn38ZBZBw9CYR38LeNblIX1seW3DXuAh1lbBYveZBZCnias2lSPXQ7w5umnoGZC1VM
  secret: 2bb2a236b7335cc58fc1c66d686e4f2a

socketio:
  user_message_evt: user_uttered
  bot_message_evt: bot_uttered
  session_persistence: false